# fly.toml app configuration file generated for phonebookv222232524 on 2023-07-18T19:12:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebookv222232524"
primary_region = "ams"

[env] 
PORT = "8080"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
