POST http://localhost:3004/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "awdsdeawdtest4",
    "author": "asdaasdwdt"
    
}
###

GET http://localhost:3003/api/blogs

###


GET http://localhost:3002/api/info


###
DELETE http://localhost:3004/api/blogs/6


###
PUT http://localhost:3004/api/blogs/64b7d77c083e9a1ad63120d5
content-type: application/json

    {
        "title": "test",
        "author": "test",
        "url": "test",
        "likes": 9,
        "id": "64b7d77c083e9a1ad63120d5"
}

###

POST http://localhost:3004/api/users HTTP/1.1
content-type: application/json

{
    "username": "Garipboi",
    "name": "Garip Kont",
    "password": "Bark"
}
###

