POST http://localhost:3004/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "awdsdetest4",
    "author": "asdawdt"
    
}
###

GET http://localhost:3003/api/blogs

###


GET http://localhost:3002/api/info


###
DELETE http://localhost:3002/api/persons/:id